# Generated by Django 5.2.2 on 2025-07-14 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id_ciudadano', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('no_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_persona', models.CharField(choices=[('victima', 'Víctima'), ('testigo', 'Testigo'), ('familiar', 'Familiar')], default='victima', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(default='user', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIncidente',
            fields=[
                ('id_tipoincidente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.IntegerField(blank=True, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('referencias', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id_incidente', models.AutoField(primary_key=True, serialize=False)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('descripcion', models.TextField()),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('id_ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.ciudadano')),
                ('id_tipoincidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.tipoincidente')),
                ('id_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.ubicacion')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.usuario')),
            ],
        ),
    ]
